export enum Pollutant {
  AtmosphericPressure = 'AtmosphericPressure',
  Temperature = 'Temperature',
  RelativeHumidity = 'RelativeHumidity',
  PM1 = 'PM1',
  PM4 = 'PM4',
  PM10 = 'PM10',
  PM25 = 'PM25',
  TotalSuspendedParticulate = 'TotalSuspendedParticulate',
  NO = 'NO',
  NO2 = 'NO2',
  NOx = 'NOx',
}
export const PollutantType = {
  AtmosphericPressure: 'Lufttryck (hPa)',
  Temperature: 'Temperatur (°C)',
  RelativeHumidity: 'Relativ Luftfuktighet (%)',
  PM1: 'PM1 (µg/m³)',
  PM4: 'PM4 (µg/m³)',
  PM10: 'PM10 (µg/m³)',
  PM25: 'PM2.5 (µg/m³)',
  TotalSuspendedParticulate: 'TSP (µg/m³)',
  NO: 'NO (µg/m³)',
  NO2: 'NO2 (µg/m³)',
  NOx: 'NOx (µg/m³)',
};

export const PollutantColor = {
  AtmosphericPressure: 'purple',
  Temperature: 'lightgreen',
  RelativeHumidity: 'darkblue',
  PM1: 'brown',
  PM4: 'cyan',
  PM10: 'grey',
  PM25: 'black',
  TotalSuspendedParticulate: 'red',
  NO: 'orange',
  NO2: 'darkgreen',
  NOx: 'magenta',
};
